<a href="https://colab.research.google.com/github/vngeno/E-COMMERCE-RECOMMENDATION-SYSTEM-/blob/main/Collaborative_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report,roc_auc_score,roc_curve,r2_score,recall_score,confusion_matrix,precision_recall_curve
from collections import Counter
from sklearn.model_selection import StratifiedKFold,KFold,StratifiedShuffleSplit
from nltk import word_tokenize
from nltk.corpus import stopwords
# stop_words = stopwords.words('english')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA, TruncatedSVD,SparsePCA
from sklearn.metrics import classification_report,confusion_matrix
from nltk.tokenize import word_tokenize
from collections import defaultdict
from collections import Counter
import seaborn as sns
from wordcloud import WordCloud,STOPWORDS
import nltk
from nltk.corpus import stopwords
import string
from plotly import tools
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go

In [ ]:
!pip install wandb

     |████████████████████████████████| 1.7 MB 5.2 MB/s 
     |████████████████████████████████| 180 kB 60.1 MB/s 
     |████████████████████████████████| 97 kB 6.6 MB/s 
     |████████████████████████████████| 139 kB 55.9 MB/s 
     |████████████████████████████████| 63 kB 1.7 MB/s 
  Created wheel for subprocess32: filename=subprocess32-3.5.4-py3-none-any.whl size=6502 sha256=02b4586c046e61d30618a9de7fd69d3cf6f5ecf29358b3963d57cbdff7d37a56
  Stored in directory: /root/.cache/pip/wheels/50/ca/fa/8fca8d246e64f19488d07567547ddec8eb084e8c0d7a59226a
  Created wheel for pathtools: filename=pathtools-0.1.2-py3-none-any.whl size=8807 sha256=f2e7b4957c439a15b5216c6a89c2db1efc5505faf9c9fa0b45edea32c4e07cc7
  Stored in directory: /root/.cache/pip/wheels/3e/31/09/fa59cef12cdcfecc627b3d24273699f390e71828921b2cbba2
Successfully built subprocess32 pathtools


In [ ]:
#loading the data set
df = pd.read_csv("/content/drive/Shareddrives/Team Stars/Data/df_clean.csv",index_col=0)
df.head(2)

id  ... reviews_username
0  AVpgNzjwLJeJML43Kpxn  ...       Byger yang
1  AVpgNzjwLJeJML43Kpxn  ...             ByMG

[2 rows x 11 columns]

In [ ]:

counts = df['reviews_username'].value_counts()
df_final = df[df['reviews_username'].isin(counts[counts >= 5].index)]
print('The number of observations in the final data =', len(df_final))
print('Number of unique USERS in the final data = ', df_final['reviews_username'].nunique())
print('Number of unique PRODUCTS in the final data = ', df_final['id'].nunique())

The number of observations in the final data = 4453
Number of unique USERS in the final data =  435
Number of unique PRODUCTS in the final data =  37


In [ ]:
df_final.drop_duplicates()

id  ...   reviews_username
1      AVpgNzjwLJeJML43Kpxn  ...               ByMG
6      AVpgNzjwLJeJML43Kpxn  ...  ByAmazon Customer
15     AVpgNzjwLJeJML43Kpxn  ...  ByAmazon Customer
18     AVpgNzjwLJeJML43Kpxn  ...             ByAdam
19     AVpgNzjwLJeJML43Kpxn  ...  ByAmazon Customer
...                     ...  ...                ...
28285  AVqkIhxunnc1JgDc3kg_  ...               Aria
28286  AVqkIhxunnc1JgDc3kg_  ...               Doug
28292  AVqkIhxunnc1JgDc3kg_  ...             Sammie
28312  AVqkIhxunnc1JgDc3kg_  ...               Jake
28314  AVqkIhxunnc1JgDc3kg_  ...              Craig

[4453 rows x 11 columns]

In [ ]:
#Creating the interaction matrix of products and users based on ratings and replacing NaN value with 0
final_ratings_matrix = df_final.pivot_table(index = 'reviews_username', columns ='name', values = 'reviews_rating').fillna(0)
print('Shape of final_ratings_matrix: ', final_ratings_matrix.shape)

#Finding the number of non-zero entries in the interaction matrix 
given_num_of_ratings = np.count_nonzero(final_ratings_matrix)
print('given_num_of_ratings = ', given_num_of_ratings)

#Finding the possible number of ratings as per the number of users and products
possible_num_of_ratings = final_ratings_matrix.shape[0] * final_ratings_matrix.shape[1]
print('possible_num_of_ratings = ', possible_num_of_ratings)

#Density of ratings
density = (given_num_of_ratings/possible_num_of_ratings)
density *= 100
print ('density: {:4.2f}%'.format(density))

final_ratings_matrix.head()

Shape of final_ratings_matrix:  (435, 37)
given_num_of_ratings =  2119
possible_num_of_ratings =  16095
density: 13.17%


name              All-New Fire 7 Tablet with Alexa, 7" Display, 8 GB - Marine Blue  ...  Kindle Voyage E-reader, 6 High-Resolution Display (300 ppi) with Adaptive Built-in Light, PagePress Sensors, Wi-Fi - Includes Special Offers
reviews_username                                                                    ...                                                                                                                                              
1234                                                            0.0                 ...                                                0.0                                                                                           
2k4k                                                            0.0                 ...                                                0.0                                                                                           
54035723                                                        0.0                 ...                                                0.0                                                                                           
ATomP                                                           0.0                 ...                                                0.0                                                                                           
Alan                                                            0.0                 ...                                                0.0                                                                                           

[5 rows x 37 columns]

**Rank Based Recommendation System**

In [ ]:
#Calculate the average rating for each product 
average_rating = df_final.groupby(['name']).mean().reviews_rating
#Calculate the count of ratings for each product
count_rating = df_final.groupby(['name']).count().reviews_rating

#Create a dataframe with calculated average and count of ratings
final_rating = pd.DataFrame(pd.concat([average_rating,count_rating], axis = 1))
final_rating.columns=["Average Rating", "Ratings Count"]

#Sort the dataframe by average of ratings
final_rating = final_rating.sort_values(by='Average Rating', ascending=False)

final_rating.head()

Average Rating  Ratings Count
name                                                                             
Kindle Voyage E-reader, 6 High-Resolution Displ...             5.0              3
Fire TV Stick Streaming Media Player Pair Kit                  5.0              3
Amazon Echo – White                                          5.0              2
All-new Echo (2nd Generation) with improved sou...             5.0              1
All-New Kindle E-reader - Black, 6" Glare-Free ...             5.0              1

In [ ]:
#defining a function to get the top n products based on highest average rating and minimum interactions
def top_n_products(final_rating, n, min_interaction):
    
    #Finding movies with minimum number of interactions
    recommendations = final_rating[final_rating['Ratings Count'] >= min_interaction]
    
    #Sorting values w.r.t average rating 
    recommendations = recommendations.sort_values(by='Average Rating', ascending=False)
    
    return recommendations.index[:n]

In [ ]:
#Recommending top 10 products with 5 minimum interactions based on popularity
list(top_n_products(final_rating, 10, 5))

['Amazon 9W PowerFast Official OEM USB Charger and Power Adapter for Fire Tablets and Kindle eReaders',
 'All-New Kindle Oasis E-reader - 7 High-Resolution Display (300 ppi), Waterproof, Built-In Audible, 8 GB, Wi-Fi - Includes Special Offers',
 'All-New Fire HD 8 Kids Edition Tablet, 8 HD Display, 32 GB, Blue Kid-Proof Case',
 'All-New Fire HD 8 Tablet with Alexa, 8 HD Display, 32 GB, Marine Blue - with Special Offers',
 'Kindle Voyage E-reader, 6 High-Resolution Display (300 ppi) with Adaptive Built-in Light, PagePress Sensors, Wi-Fi - Includes Special Offers',
 'All-New Fire HD 8 Kids Edition Tablet, 8 HD Display, 32 GB, Pink Kid-Proof Case',
 'All-New Fire 7 Tablet with Alexa, 7" Display, 8 GB - Marine Blue',
 'All-New Fire HD 8 Tablet with Alexa, 8 HD Display, 16 GB, Marine Blue - with Special Offers',
 'Amazon Tap Smart Assistant Alexaenabled (black) Brand New',
 'Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16 GB, Green Kid-Proof Case']

# KNN

In [ ]:
#picking the required columns
dataset=df[['id','reviews_username','reviews_rating']]
dataset.head()

id  reviews_username  reviews_rating
0  AVpgNzjwLJeJML43Kpxn        Byger yang               3
1  AVpgNzjwLJeJML43Kpxn              ByMG               4
2  AVpgNzjwLJeJML43Kpxn  BySharon Lambert               5
3  AVpgNzjwLJeJML43Kpxn     Bymark sexson               5
4  AVpgNzjwLJeJML43Kpxn           Bylinda               5

In [ ]:
## First lets create a Pivot matrix

product_matrix=dataset.pivot_table(index='id',columns='reviews_username',values='reviews_rating')
product_matrix.sample(5)

reviews_username      000G  00Gambler  1000011  ...  ziggy24  zmax192  ztlbxx
id                                              ...                          
AVpjEN4jLJeJML43rpUe   NaN        NaN      NaN  ...      NaN      NaN     NaN
AVpi6NtY1cnluZ0-RuRs   NaN        NaN      NaN  ...      NaN      NaN     NaN
AVqVGZN9QMlgsOJE6eUZ   NaN        NaN      NaN  ...      NaN      NaN     NaN
AVqkIdZiv8e3D1O-leaJ   NaN        NaN      NaN  ...      NaN      NaN     NaN
AVpe5Q3sLJeJML43xt5X   NaN        NaN      NaN  ...      NaN      NaN     NaN

[5 rows x 16269 columns]

In [ ]:
product_matrix.fillna(0,inplace=True)
product_matrix.head()

reviews_username      000G  00Gambler  1000011  ...  ziggy24  zmax192  ztlbxx
id                                              ...                          
AV-ETMhgYSSHbkXwpNb9   0.0        0.0      0.0  ...      0.0      0.0     0.0
AV-EVZITKZqtpbFMSoqc   0.0        0.0      0.0  ...      0.0      0.0     0.0
AV2ElNnuvKc47QAVouhY   0.0        0.0      0.0  ...      0.0      0.0     0.0
AVpe5Q3sLJeJML43xt5X   0.0        0.0      0.0  ...      0.0      0.0     0.0
AVpe6nyKLJeJML43yOe2   0.0        0.0      0.0  ...      0.0      0.0     0.0

[5 rows x 16269 columns]

In [ ]:
# Applying the csr_matrix method to the dataset :
from scipy.sparse import csr_matrix
csr_data = csr_matrix(product_matrix.values)
product_matrix.reset_index(inplace=True)

In [ ]:
#applying nearest neighbours
from sklearn.neighbors import NearestNeighbors
# All regression plots

knn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=15, n_jobs=-1)
knn.fit(csr_data)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=-1, n_neighbors=15, p=2,
                 radius=1.0)

In [ ]:
#recommending the product
def product_recommendation(product_name):
    n_products_to_reccomend = 4
    product_list = df[df['name']==product_name]
    
    if len(product_list):        
        product_idx= product_list.iloc[0]['id']
        product_idx = product_matrix[product_matrix['id'] == product_idx].index
        distances , indices = knn.kneighbors(csr_data[product_idx],n_neighbors=n_products_to_reccomend+1) 
        rec_product_indices = sorted(list(zip(indices.squeeze().tolist(),distances.squeeze().tolist())),key=lambda x: x[1])[:0:-1]
        recommend_frame = []
        for val in rec_product_indices:
            product_idx = product_matrix.iloc[val[0]]['id']
            idx = df[df['id'] == product_idx].index
            recommend_frame.append({'name':df.iloc[idx]['name'].values[0],'Distance':val[1]})
        
        data = pd.DataFrame(recommend_frame,index=range(1,n_products_to_reccomend+1))
        return data
    else:
        return "No product found try another product"


In [ ]:
#predicting the 2000th name
product_recommendation(df['name'][2000])


name  Distance
1  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...  1.000000
2  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...  1.000000
3  Fire HD 8 Tablet with Alexa, 8 HD Display, 16 ...  1.000000
4  AmazonBasics AA Performance Alkaline Batteries...  0.610451

## Memory Recommenders

**Collaborative Filtering based Recommendation System**

In [ ]:
final_ratings_matrix.head()

name              All-New Fire 7 Tablet with Alexa, 7" Display, 8 GB - Marine Blue  ...  Kindle Voyage E-reader, 6 High-Resolution Display (300 ppi) with Adaptive Built-in Light, PagePress Sensors, Wi-Fi - Includes Special Offers
reviews_username                                                                    ...                                                                                                                                              
1234                                                            0.0                 ...                                                0.0                                                                                           
2k4k                                                            0.0                 ...                                                0.0                                                                                           
54035723                                                        0.0                 ...                                                0.0                                                                                           
ATomP                                                           0.0                 ...                                                0.0                                                                                           
Alan                                                            0.0                 ...                                                0.0                                                                                           

[5 rows x 37 columns]

In [ ]:
final_ratings_matrix['user_index'] = np.arange(0, final_ratings_matrix.shape[0])
final_ratings_matrix.set_index(['user_index'], inplace=True)

# Actual ratings given by users
final_ratings_matrix.head()

name        All-New Fire 7 Tablet with Alexa, 7" Display, 8 GB - Marine Blue  ...  Kindle Voyage E-reader, 6 High-Resolution Display (300 ppi) with Adaptive Built-in Light, PagePress Sensors, Wi-Fi - Includes Special Offers
user_index                                                                    ...                                                                                                                                              
0                                                         0.0                 ...                                                0.0                                                                                           
1                                                         0.0                 ...                                                0.0                                                                                           
2                                                         0.0                 ...                                                0.0                                                                                           
3                                                         0.0                 ...                                                0.0                                                                                           
4                                                         0.0                 ...                                                0.0                                                                                           

[5 rows x 37 columns]

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import mean_squared_error# defining a function to get similar users

def similar_users(user_index, interactions_matrix):
    similarity = []
    for user in range(0, interactions_matrix.shape[0]):
        
        #finding cosine similarity between the user_id and each user
        sim = cosine_similarity([interactions_matrix.loc[user_index]], [interactions_matrix.loc[user]])
        
        #Appending the user and the corresponding similarity score with user_id as a tuple
        similarity.append((user, sim))
        
    similarity.sort(key=lambda x: x[1], reverse=True)
    most_similar_users = [Tuple[0] for Tuple in similarity] #Extract the user from each tuple in the sorted list
    similarity_score = [Tuple[1] for Tuple in similarity]   ##Extracting the similarity score from each tuple in the sorted list
   
    #Remove the original user and its similarity score and keep only other similar users 
    most_similar_users.remove(user_index)
    similarity_score.remove(similarity_score[0])
       
    return most_similar_users, similarity_score

In [ ]:
similar = similar_users(3, final_ratings_matrix)[0][0:10]
similar

[19, 23, 127, 131, 189, 235, 260, 276, 298, 374]

In [ ]:
#Print the similarity score
similar_users(3,final_ratings_matrix)[1][0:10]

[array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]]),
 array([[1.]])]

In [ ]:
# defining a function to get similar users
def similar_users(user_index, interactions_matrix):
    similarity = []
    for user in range(0, interactions_matrix.shape[0]):
        
        #finding cosine similarity between the user_id and each user
        sim = cosine_similarity([interactions_matrix.loc[user_index]], [interactions_matrix.loc[user]])
        
        #Appending the user and the corresponding similarity score with user_id as a tuple
        similarity.append((user, sim))
        
    similarity.sort(key=lambda x: x[1], reverse=True)
    most_similar_users = [Tuple[0] for Tuple in similarity] #Extract the user from each tuple in the sorted list
    similarity_score = [Tuple[1] for Tuple in similarity]   ##Extracting the similarity score from each tuple in the sorted list
   
    #Remove the original user and its similarity score and keep only other similar users 
    most_similar_users.remove(user_index)
    similarity_score.remove(similarity_score[0])
       
    return most_similar_users, similarity_score

In [ ]:
similar = similar_users(3, final_ratings_matrix)[0][0:10]
similar

[19, 23, 127, 131, 189, 235, 260, 276, 298, 374]

In [ ]:
# defining the recommendations function to get recommendations by using the similar users' preferences
def recommendations(user_index, num_of_products, interactions_matrix):
    
    #Saving similar users using the function similar_users defined above
    most_similar_users = similar_users(user_index, interactions_matrix)[0]
    
    #Finding product IDs with which the user_id has interacted
    prod_ids = set(list(interactions_matrix.columns[np.where(interactions_matrix.loc[user_index] > 0)]))
    recommendations = []
    
    observed_interactions = prod_ids.copy()
    for similar_user in most_similar_users:
        if len(recommendations) < num_of_products:
            
            #Finding 'n' products which have been rated by similar users but not by the user_id
            similar_user_prod_ids = set(list(interactions_matrix.columns[np.where(interactions_matrix.loc[similar_user] > 0)]))
            recommendations.extend(list(similar_user_prod_ids.difference(observed_interactions)))
            observed_interactions = observed_interactions.union(similar_user_prod_ids)
        else:
            break
    
    return recommendations[:num_of_products]

In [ ]:
recommendations(3, 5, final_ratings_matrix)

['Amazon Tap Smart Assistant Alexaenabled (black) Brand New',
 'Fire Tablet with Alexa, 7 Display, 16 GB, Magenta - with Special Offers',
 'Fire Tablet with Alexa, 7 Display, 16 GB, Blue - with Special Offers',
 'Fire HD 8 Tablet with Alexa, 8 HD Display, 16 GB, Tangerine - with Special Offers',
 'All-New Fire HD 8 Tablet with Alexa, 8 HD Display, 32 GB, Marine Blue - with Special Offers']

## Singular Value Decomposition

In [ ]:
from scipy.sparse.linalg import svds # for sparse matrices

# Singular Value Decomposition
U, s, Vt = svds(final_ratings_matrix, k = 5) # here k is the number of latent features

# Construct diagonal array in SVD
sigma = np.diag(s)

In [ ]:
U.shape #checking the shape of the U matrix

(435, 5)

In [ ]:
sigma.shape #checking the shape of the sigma matrix

(5, 5)

In [ ]:
Vt.shape #checking the shape of the Vt matrix

(5, 37)

In [ ]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) 

# Predicted ratings
preds_df = pd.DataFrame(abs(all_user_predicted_ratings), columns = final_ratings_matrix.columns)
preds_df.head()

name  All-New Fire 7 Tablet with Alexa, 7" Display, 8 GB - Marine Blue  ...  Kindle Voyage E-reader, 6 High-Resolution Display (300 ppi) with Adaptive Built-in Light, PagePress Sensors, Wi-Fi - Includes Special Offers
0                                              0.134197                 ...                                           0.627927                                                                                           
1                                              0.427584                 ...                                           0.557807                                                                                           
2                                              0.002766                 ...                                           0.148466                                                                                           
3                                              0.002212                 ...                                           0.118773                                                                                           
4                                              0.022935                 ...                                           0.128713                                                                                           

[5 rows x 37 columns]

In [ ]:
# Recommend the items with the highest predicted ratings

def recommend_items(user_index, interactions_matrix, preds_df, num_recommendations):
    
    # Get and sort the user's ratings from the actual and predicted interaction matrix
    sorted_user_ratings = interactions_matrix.loc[user_index].sort_values(ascending=False)
    sorted_user_predictions = preds_df.loc[user_index].sort_values(ascending=False)

    #Creating a dataframe with actual and predicted ratings columns
    temp = pd.concat([sorted_user_ratings, sorted_user_predictions], axis=1)
    temp.index.name = 'Recommended Products'
    temp.columns = ['user_ratings', 'user_predictions']
    
    #Filtering the dataframe where actual ratings are 0 which implies that the user has not interacted with that product
    temp = temp.loc[temp['user_ratings'] == 0]   
    
    #Recommending products with top predicted ratings
    temp = temp.sort_values(by='user_predictions', ascending=False) #Sort the dataframe by user_predictions in descending order
    print('\nBelow are the recommended products for user(user_id = {}):\n'.format(user_index))
    print(temp['user_predictions'].head(num_recommendations))

In [ ]:
#Enter 'user index' and 'num_recommendations' for the user
recommend_items(121, final_ratings_matrix, preds_df, 5)


Below are the recommended products for user(user_id = 121):

Recommended Products
All-New Fire HD 8 Tablet with Alexa, 8 HD Display, 16 GB, Marine Blue - with Special Offers                                                     1.217662
Amazon Tap Smart Assistant Alexaenabled (black) Brand New                                                                                       1.027543
Kindle Voyage E-reader, 6 High-Resolution Display (300 ppi) with Adaptive Built-in Light, PagePress Sensors, Wi-Fi - Includes Special Offers    0.831582
All-New Fire HD 8 Kids Edition Tablet, 8 HD Display, 32 GB, Blue Kid-Proof Case                                                                 0.579113
Kindle E-reader - White, 6 Glare-Free Touchscreen Display, Wi-Fi - Includes Special Offers                                                      0.436662
Name: user_predictions, dtype: float64


In [ ]:
# Actual ratings given by the users
final_ratings_matrix.head()

name        All-New Fire 7 Tablet with Alexa, 7" Display, 8 GB - Marine Blue  ...  Kindle Voyage E-reader, 6 High-Resolution Display (300 ppi) with Adaptive Built-in Light, PagePress Sensors, Wi-Fi - Includes Special Offers
user_index                                                                    ...                                                                                                                                              
0                                                         0.0                 ...                                                0.0                                                                                           
1                                                         0.0                 ...                                                0.0                                                                                           
2                                                         0.0                 ...                                                0.0                                                                                           
3                                                         0.0                 ...                                                0.0                                                                                           
4                                                         0.0                 ...                                                0.0                                                                                           

[5 rows x 37 columns]

In [ ]:
# Find average actual rating for each item
final_ratings_matrix.mean()

name
All-New Fire 7 Tablet with Alexa, 7" Display, 8 GB - Marine Blue                                                                                          0.117241
All-New Fire HD 8 Kids Edition Tablet, 8 HD Display, 32 GB, Blue Kid-Proof Case                                                                           0.319540
All-New Fire HD 8 Kids Edition Tablet, 8 HD Display, 32 GB, Pink Kid-Proof Case                                                                           0.385057
All-New Fire HD 8 Tablet with Alexa, 8 HD Display, 16 GB, Marine Blue - with Special Offers                                                               0.710345
All-New Fire HD 8 Tablet with Alexa, 8 HD Display, 32 GB, Marine Blue - with Special Offers                                                               0.187356
All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi, 16 GB - Includes Special Offers, Black                                                                     1.814331
All-New Fire HD 8

In [ ]:
#create a dataframe containing average actual ratings and avearge predicted ratings for each product
rmse_df = pd.concat([final_ratings_matrix.mean(), preds_df.mean()], axis=1)

rmse_df.columns = ['Avg_actual_ratings', 'Avg_predicted_ratings']

rmse_df.head()

Avg_actual_ratings  Avg_predicted_ratings
name                                                                                         
All-New Fire 7 Tablet with Alexa, 7" Display, 8...            0.117241               0.116892
All-New Fire HD 8 Kids Edition Tablet, 8 HD Dis...            0.319540               0.318145
All-New Fire HD 8 Kids Edition Tablet, 8 HD Dis...            0.385057               0.402301
All-New Fire HD 8 Tablet with Alexa, 8 HD Displ...            0.710345               0.757016
All-New Fire HD 8 Tablet with Alexa, 8 HD Displ...            0.187356               0.209931

In [ ]:
#Calculate and print RMSE using the mean_square_error function
RMSE = mean_squared_error(rmse_df['Avg_actual_ratings'], rmse_df['Avg_predicted_ratings'], squared=False)
print('\nRMSE SVD Model = {} \n'.format(RMSE))


RMSE SVD Model = 0.03380476263314368 



In [ ]:
# Enter 'user_index' and 'num_recommendations' for the user #
recommend_items(100, final_ratings_matrix, preds_df, 10)


Below are the recommended products for user(user_id = 100):

Recommended Products
Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16 GB, Pink Kid-Proof Case                                                              1.886466e-15
Fire Tablet with Alexa, 7 Display, 16 GB, Magenta - with Special Offers                                                             1.884683e-15
Fire Tablet, 7 Display, Wi-Fi, 16 GB - Includes Special Offers, Black                                                               1.783366e-15
Kindle E-reader - White, 6 Glare-Free Touchscreen Display, Wi-Fi - Includes Special Offers                                          1.600918e-15
Fire Tablet with Alexa, 7 Display, 16 GB, Blue - with Special Offers                                                                1.497115e-15
Amazon Tap Smart Assistant Alexaenabled (black) Brand New                                                                           1.126042e-15
Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16 